package com.AirBnb.TimberAndStone.models;

public enum AmenityTitle {
    PETSALLOWED, TV, KITCHEN, POOL, AC, DISHWASHER, SHOWER, BATHTUB,
    HOTTUB, GRILL, VIEW, OVEN, STOVE, PORCH, BALCONY, WORKSPACE, NETWORK,
    ELECTRICITY, WATER, HEAT, FIREPLACE, SAUNA, CLOSET, ENSUITE, HAIRDRYER,
    PARKING, BREAKFAST, WASHINGMACHINE, DRYER, FREEZER, REFRIGERATOR, BEDS, OTHER;
}
